default['megam_riak']="api.megam.co"
default['megam_rabbitmq']="www.megam.co"
default['megam_monitor']="monitor.megam.co.in"
default['megam_kibana']="monitor.megam.co.in"
default['megam_etcd']="etcd.megam.co.in"
