source "https://supermarket.getchef.com"

metadata



group :integration do
  cookbook "megam_metering", :path => '~/chef/chef-repo/cookbooks/megam_metering'
  cookbook "megam_tomcat", :path => '~/chef/chef-repo/cookbooks/megam_tomcat'

  cookbook "apt", :path => '~/chef/chef-repo/cookbooks/apt'

  cookbook "git", :path => '~/chef/chef-repo/cookbooks/git'

  cookbook "megam_dns", :path => '~/chef/chef-repo/cookbooks/megam_dns'

  cookbook "megam_deps", :path => '~/chef/chef-repo/cookbooks/megam_deps'

  cookbook "megam_logging", :path => '~/chef/chef-repo/cookbooks/megam_logging'

  cookbook "megam_gulp", :path => '~/chef/chef-repo/cookbooks/megam_gulp'

  cookbook "megam_environment", :path => '~/chef/chef-repo/cookbooks/megam_environment'

  cookbook "megam_preinstall", :path => '~/chef/chef-repo/cookbooks/megam_preinstall'

end


 
